"""End-to-end check of the Unreal half, before any extraction exists.

Builds a synthetic Del Perro Pier from the real world coordinates, runs it through the verified
GTA->UE transform, writes a region.json, reloads it, validates it and dry-runs the spawner.

The point is that the ingest side can be wrong in ways that only show up as "the region looks
mirrored", so the geometry check at the end asserts the thing that actually catches it: the
Ferris Whale has to end up northeast of a deck running southwest, because the pier is strongly
asymmetric and a bad handedness flip puts the wheel on the wrong end.

The region.json this writes is also usable on its own: point spawn_region.py at it with cube
meshes imported under the asset root and you can prove the whole Unreal ingest before GAE
exports a single byte.
"""

import json
import math
import os
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "ue"))
sys.path.insert(0, HERE)

from region_manifest import Region, Cell, Instance, Archetype, ManifestError, CONVENTION  # noqa
import test_transform_convention as tc  # noqa  -- reuse the proven transform, never a second copy

import spawn_region  # noqa


def gta_quat_stored_from_yaw(deg):
    """A yaw about Z as a ymap would store it: the conjugate of the actual rotation."""
    th = math.radians(deg)
    q = (0.0, 0.0, math.sin(th / 2), math.cos(th / 2))
    return (-q[0], -q[1], -q[2], q[3])


def build_pier():
    """
    Del Perro Pier, from the coordinates in CLAUDE.md. Runs southwest from about
    (-1660, -1120) to (-1885, -1225), upper deck z ~ 12.9, Ferris Whale at
    (-1663.97, -1126.74, 29.32), sea level z = 0.
    """
    start = (-1660.0, -1120.0, 12.9)
    end = (-1885.0, -1225.0, 12.9)
    sections = 12

    heading = math.degrees(math.atan2(end[1] - start[1], end[0] - start[0]))
    cells, deck, pilings = [], [], []

    for i in range(sections):
        t = i / (sections - 1)
        pos = tuple(s + (e - s) * t for s, e in zip(start, end))
        deck.append(Instance(
            archetype="prop_pier_deck_01",
            position=tc.transform_position(pos),
            rotation=tc.transform_quaternion(gta_quat_stored_from_yaw(heading)),
            scale=tc.transform_scale(1.0, 1.0),
            lod_level=0, lod_dist=500.0, guid=1000 + i))
        for side in (-4.0, 4.0):
            off = (pos[0] + side * math.sin(math.radians(heading)),
                   pos[1] - side * math.cos(math.radians(heading)),
                   0.0)
            pilings.append(Instance(
                archetype="prop_pier_piling_01",
                position=tc.transform_position(off),
                rotation=tc.transform_quaternion((0.0, 0.0, 0.0, 1.0)),
                scale=tc.transform_scale(1.0, 1.45),   # non-uniform on purpose
                lod_level=0, lod_dist=300.0, guid=2000 + len(pilings)))

    wheel = Instance(
        archetype="prop_ferris_wheel",
        position=tc.transform_position((-1663.97, -1126.74, 29.32)),
        rotation=tc.transform_quaternion(gta_quat_stored_from_yaw(heading + 90.0)),
        scale=tc.transform_scale(1.0, 1.0),
        lod_level=0, lod_dist=1500.0, guid=3000)

    cells.append(Cell("vb_01_pier", hash=0x1111, instances=deck + [wheel]))
    cells.append(Cell("vb_02_pilings", hash=0x2222, parent="vb_01_pier", instances=pilings))

    archetypes = {
        "prop_pier_deck_01":   Archetype("prop_pier_deck_01", 0xAA01, "Meshes/prop_pier_deck_01.gltf",
                                         [-10, -5, -0.5], [10, 5, 0.5], 500.0,
                                         "vb_props", "x64m.rpf\\...\\venice_01\\vb_01.rpf"),
        "prop_pier_piling_01": Archetype("prop_pier_piling_01", 0xAA02, "Meshes/prop_pier_piling_01.gltf",
                                         [-0.5, -0.5, 0], [0.5, 0.5, 14], 300.0,
                                         "vb_props", "x64m.rpf\\...\\venice_01\\vb_01.rpf"),
        "prop_ferris_wheel":   Archetype("prop_ferris_wheel", 0xAA03, "Meshes/prop_ferris_wheel.gltf",
                                         [-16.5, -16.5, -17], [16.5, 16.5, 16], 1500.0,
                                         "vb_props", "x64m.rpf\\...\\venice_01\\vb_01.rpf"),
    }

    return Region(
        source={"game": "GTA V", "edition": "unknown (synthetic fixture)",
                "note": "generated by tools/test_ue_spawn.py, not extracted"},
        bounds={"gta_min": [-1950, -1400, -30], "gta_max": [-1450, -850, 80]},
        archetypes=archetypes, cells=cells)


def main():
    ok = True

    def check(label, cond, detail=""):
        nonlocal ok
        ok &= bool(cond)
        print(f"  {'PASS' if cond else 'FAIL'}  {label}" + (f"   {detail}" if detail and not cond else ""))

    region = build_pier()
    print(region.describe())
    print()

    tmp = tempfile.mkdtemp()
    path = os.path.join(tmp, "region.json")
    region.save(path)

    # Placeholder files so the fixture is self-consistent. The exporter writes real glTF here;
    # what matters for this test is that the paths in the manifest resolve.
    os.makedirs(os.path.join(tmp, "Meshes"), exist_ok=True)
    for arch in region.archetypes.values():
        open(os.path.join(tmp, arch.asset), "wb").close()

    print("Round trip")
    reloaded = Region.load(path)
    check("instance count survives", reloaded.stats()["instances"] == region.stats()["instances"])
    check("archetype count survives", len(reloaded.archetypes) == len(region.archetypes))
    check("cell parent link survives", reloaded.cells[1].parent == "vb_01_pier")
    a = next(i for _, i in region.all_instances() if i.archetype == "prop_ferris_wheel")
    b = next(i for _, i in reloaded.all_instances() if i.archetype == "prop_ferris_wheel")
    check("transform survives byte for byte", a.position == b.position and a.rotation == b.rotation)
    check("non-uniform scale survives",
          any(i.scale[0] != i.scale[2] for _, i in reloaded.all_instances()))

    print("\nConvention guard")
    with open(path) as f:
        d = json.load(f)
    d["convention"]["position"] = "ue = (gta.x, -gta.y, gta.z) * 100"
    bad = os.path.join(tmp, "bad.json")
    with open(bad, "w") as f:
        json.dump(d, f)
    try:
        Region.load(bad)
        check("a manifest written with a different convention is rejected", False)
    except ManifestError:
        check("a manifest written with a different convention is rejected", True)

    print("\nValidation")
    problems = reloaded.validate(require_assets=False)
    check("a clean manifest has no problems", problems == [], f"got {problems}")

    broken = build_pier()
    broken.cells[0].instances.append(Instance("prop_that_never_resolved", [0, 0, 0], [0, 0, 0, 1], [1, 1, 1]))
    problems = broken.validate(require_assets=False)
    check("an instance referencing an unknown archetype is caught",
          any("prop_that_never_resolved" in p for p in problems), f"got {problems}")

    zero = build_pier()
    zero.cells[0].instances[0].rotation = [0, 0, 0, 0]
    check("a zero quaternion is caught", any("zero quaternion" in p for p in zero.validate(require_assets=False)))

    missing_asset = build_pier()
    missing_asset.archetypes["prop_ferris_wheel"].asset = None
    check("a referenced archetype with no exported asset is caught",
          any("no exported asset" in p for p in missing_asset.validate(require_assets=True)))

    print("\nGrouping")
    per_cell = reloaded.group_for_spawn(per_cell=True)
    flat = reloaded.group_for_spawn(per_cell=False)
    check("per-cell grouping splits deck, wheel and pilings", len(per_cell) == 3, f"got {len(per_cell)}")
    check("flat grouping collapses to one per archetype", len(flat) == 3, f"got {len(flat)}")
    check("every instance lands in exactly one group",
          sum(len(v) for v in per_cell.values()) == reloaded.stats()["instances"])

    print("\nGeometry: the check that actually catches a bad handedness flip")
    deck_positions = [i.position for _, i in reloaded.all_instances() if i.archetype == "prop_pier_deck_01"]
    wheel_pos = next(i.position for _, i in reloaded.all_instances() if i.archetype == "prop_ferris_wheel")
    far_end = max(deck_positions, key=lambda p: (p[0] - wheel_pos[0]) ** 2 + (p[1] - wheel_pos[1]) ** 2)

    # GTA: wheel is at the northeast (shore) end, deck runs southwest to (-1885, -1225).
    # UE = (gy, gx, gz), so shore-end wheel must sit at greater X and greater Y than the far end.
    check("wheel is at the shore end, not the seaward end (X)", wheel_pos[0] > far_end[0],
          f"wheel {wheel_pos[0]:.0f} vs far end {far_end[0]:.0f}")
    check("wheel is at the shore end, not the seaward end (Y)", wheel_pos[1] > far_end[1],
          f"wheel {wheel_pos[1]:.0f} vs far end {far_end[1]:.0f}")

    length_cm = math.dist(far_end[:2], wheel_pos[:2])
    check("pier reads about 250 m, matching Del Perro rather than the real 500 m pier",
          20000 < length_cm < 30000, f"got {length_cm/100:.0f} m")

    deck_z = deck_positions[0][2]
    check("deck sits at 1290 cm above a sea level of 0", abs(deck_z - 1290.0) < 1e-6, f"got {deck_z}")

    print("\nSpawner dry run (no editor)")
    summary = spawn_region.run(path, dry_run=True, log=lambda m: None)
    check("dry run reports the same instance total", summary["instances"] == reloaded.stats()["instances"])
    check("dry run reports the group count", summary["groups"] == len(per_cell))
    check("a clean manifest dry-runs with no problems", summary["problems"] == 0,
          f"got {summary['problems']}")

    print("\nThe guard that matters: a partial region must not spawn silently")
    os.remove(os.path.join(tmp, region.archetypes["prop_ferris_wheel"].asset))
    try:
        spawn_region.run(path, dry_run=True, log=lambda m: None)
        check("a missing exported asset hard-fails instead of quietly skipping", False)
    except ManifestError as e:
        check("a missing exported asset hard-fails instead of quietly skipping",
              "prop_ferris_wheel" in str(e) or "problem" in str(e))
    summary = spawn_region.run(path, dry_run=True, allow_missing=True, log=lambda m: None)
    check("allow_missing is the deliberate opt-out, and still reports the problem",
          summary["problems"] == 1, f"got {summary['problems']}")
    open(os.path.join(tmp, region.archetypes["prop_ferris_wheel"].asset), "wb").close()

    try:
        spawn_region.run(os.path.join(tmp, "nope.json"), dry_run=True, log=lambda m: None)
        check("a missing manifest raises", False)
    except (FileNotFoundError, OSError):
        check("a missing manifest raises", True)

    print(f"\nfixture written to {path}")
    print("ALL PASS" if ok else "FAILURES ABOVE")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
